# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ctd-backend-new

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a7cd4cde08b546b19ce526a185375ae7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f54cc8ba245a4a308a9bb0fb3be95ffa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a7cd4cde08b546b19ce526a185375ae7 }}/ady1506/ctd-azure-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ctd-backend-new'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_73c6c0dfc0f24614ab93c998b4b68c9b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a7cd4cde08b546b19ce526a185375ae7 }}/ady1506/ctd-azure-backend:${{ github.sha }}'